export const foodDatabase = [
  // Somali Foods
  {
    name: 'Bariis (Rice)',
    category: 'Somali',
    calories: 350,
    protein: 7,
    fat: 8,
    carbs: 65,
  },
  {
    name: 'Baasto (Pasta)',
    category: 'Somali',
    calories: 380,
    protein: 12,
    fat: 10,
    carbs: 68,
  },
  {
    name: 'Canjeero (Somali Pancake)',
    category: 'Somali',
    calories: 250,
    protein: 8,
    fat: 3,
    carbs: 48,
  },
  {
    name: 'Hilib Ari (Goat Meat)',
    category: 'Somali',
    calories: 280,
    protein: 35,
    fat: 15,
    carbs: 0,
  },
  {
    name: "Hilib Lo' (Beef)",
    category: 'Somali',
    calories: 320,
    protein: 32,
    fat: 22,
    carbs: 0,
  },
  {
    name: 'Caano (Milk)',
    category: 'Somali',
    calories: 150,
    protein: 8,
    fat: 8,
    carbs: 12,
  },
  {
    name: 'Cambuulo (Adzuki Beans)',
    category: 'Somali',
    calories: 220,
    protein: 14,
    fat: 1,
    carbs: 42,
  },
  
  // Common Foods
  {
    name: 'Chicken Breast',
    category: 'Protein',
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
  },
  {
    name: 'Salmon',
    category: 'Protein',
    calories: 206,
    protein: 22,
    fat: 13,
    carbs: 0,
  },
  {
    name: 'Eggs (2 large)',
    category: 'Protein',
    calories: 143,
    protein: 13,
    fat: 10,
    carbs: 1,
  },
  {
    name: 'Brown Rice',
    category: 'Grains',
    calories: 215,
    protein: 5,
    fat: 1.8,
    carbs: 45,
  },
  {
    name: 'Oatmeal',
    category: 'Grains',
    calories: 150,
    protein: 5,
    fat: 3,
    carbs: 27,
  },
  {
    name: 'Whole Wheat Bread',
    category: 'Grains',
    calories: 80,
    protein: 4,
    fat: 1,
    carbs: 14,
  },
  {
    name: 'Banana',
    category: 'Fruits',
    calories: 105,
    protein: 1.3,
    fat: 0.4,
    carbs: 27,
  },
  {
    name: 'Apple',
    category: 'Fruits',
    calories: 95,
    protein: 0.5,
    fat: 0.3,
    carbs: 25,
  },
  {
    name: 'Orange',
    category: 'Fruits',
    calories: 62,
    protein: 1.2,
    fat: 0.2,
    carbs: 15,
  },
  {
    name: 'Broccoli',
    category: 'Vegetables',
    calories: 55,
    protein: 3.7,
    fat: 0.6,
    carbs: 11,
  },
  {
    name: 'Spinach',
    category: 'Vegetables',
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
  },
  {
    name: 'Sweet Potato',
    category: 'Vegetables',
    calories: 180,
    protein: 4,
    fat: 0.3,
    carbs: 41,
  },
  {
    name: 'Almonds (28g)',
    category: 'Snacks',
    calories: 164,
    protein: 6,
    fat: 14,
    carbs: 6,
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    calories: 100,
    protein: 17,
    fat: 0.7,
    carbs: 7,
  },
  {
    name: 'Cheese (30g)',
    category: 'Dairy',
    calories: 113,
    protein: 7,
    fat: 9,
    carbs: 1,
  },
];

export const exerciseList = [
  'Push-up',
  'Squat',
  'Running',
  'Walking',
  'Cycling',
  'Swimming',
  'Jumping Jacks',
  'Plank',
  'Lunges',
  'Burpees',
  'Pull-ups',
  'Sit-ups',
  'Mountain Climbers',
  'Deadlifts',
  'Bench Press',
  'Yoga',
  'Pilates',
  'Dancing',
  'Boxing',
  'Jump Rope',
];
